### ISSUE TITLE
Description flip-flops

### ISSUE THREAD

**Issue by ryjones** [jmertic/landscape-tools#13]
Every time you run this, the description blocks flip-flop.

[Example 1](https://github.com/hyperledger-landscape/hl-landscape/blob/bc92db31bada3a8f9c8151a2c1726f758f5db597/landscape.yml#L10-L13)

[Example 2](https://github.com/hyperledger-landscape/hl-landscape/blob/master/landscape.yml#L10-L12)

**Comment by jmertic** [comment]
Yeah - this is a known and annoying issue, as the libraries that landscapeapp uses vs this are different and have some quirks on the output. I'll keep open to try to debug this again. Thanks for flagging!

**Comment by jmertic** [comment]
Fixed this by modifying the INSTRUCTIONS.md file to run some of the tools in landscapeapp to clean up the file before committing.
